### ISSUE TITLE
Should Resource miner collect Chiseled Ice?

### ISSUE THREAD

**Issue by ShaCraft** [ValkyrieofNight/EnvironmentalTech#135]
Should Resource miner collect Chiseled Ice?
![javaw 6-28-2018 1-31-04 am-436](https://user-images.githubusercontent.com/13075796/42048005-ea2d8222-7acf-11e8-98fe-d77c968d074a.png)

**Comment by Meryl** [comment]
Yes, it does indeed collect a lot of these because chisel adds these variants to the ice oredictionary (this normally only contain regular ice and packed ice).

If you wish to fix this you will have to manually edit the json files you can find in your config folder under `environmentaltech/multiblocks/void_miner/resource/tier_*.json.` You will have to edit each file individually and find a line that goes `"id": "OD_PREFIX:ice"` (or something similar, on the default config it's likely somewhere on or around line 291). Change that to say `"id": "minecraft:ice"`.

That way, you should only get regular ice.

**Comment by ValkyrieofNight** [comment]
I've changed the defaults to just use Minecraft's ice for the next release but you will need to delete the old jsons for that to take effect.
