### ISSUE TITLE
weird personal nanobot behaviour

### ISSUE THREAD

**Issue by Yoghurt4C** [ValkyrieofNight/EnvironmentalTech#153]
[server]
the beacon is functional when assembled, but changing dimensions rids you of its effects. doesn't matter whether it's forcibly chunkloaded - you can't regain the effects without rejoining the server or reassembling the structure
environmentaltech-1.12.2-2.0.15.1
forge 2757

**Comment by ValkyrieofNight** [comment]
Did you happen to update to this version from another version without reassembling your beacons because this version has a new system in place for disabling effects that is much more stable and requires the controller to be broken and placed again. This version has been tested for about a month on my server and nobody has had that issue after breaking and placing their controllers.

**Comment by Yoghurt4C** [comment]
I've only assembled the beacon on this version, and broke and replaced the controller a bunch of times
could this be a crossmod issue with `vanillafix`? iirc it messes with changing dimensions to fix vanilla bugs

**Comment by ValkyrieofNight** [comment]
Not sure but definitely make sure another mod is not interfering with chunk loading that controller

**Comment by ValkyrieofNight** [comment]
I think its probably not vanilla fix because i've also been running it on my server too

**Comment by ValkyrieofNight** [comment]
I will take a look and do a bit of testing and see if there is anything needing a fix

**Comment by OldManMining** [comment]
I have this issue, as well. I'm playing the Automaton pack. Creative flight works great in the overworld. Go to mining dimension - still works. Go to nether - no more flight. If you go to the mining dimension after being in the nether, flight is restored. Otherwise, you have to break a piece of the multiblock and replace it, restarting the beacon.

**Comment by Algester** [comment]
Also happens in my experience with stoneblock but in single player I chunk loaded with FTB utilities and no good I chunkloaded with a flux point no good

**Comment by ValkyrieofNight** [comment]
No longer updating the 1.12.2 version
