### ISSUE TITLE
1.16.4 Crafter server crash

### ISSUE THREAD

**Issue by BedrockLegends** [ValkyrieofNight/EnvironmentalTech#216]
https://github.com/refinedmods/refinedstorage/issues/2757

**Comment by BedrockLegends** [comment]
Your  using clientside code on the server.

**Comment by ReillyBrogan** [comment]
Yep, just got this as well. Identical exception.

**Comment by ReillyBrogan** [comment]
To anyone who is affected by this issue and is not able to load their worlds I have a temporary fix. Assuming you have file access to your server you can copy your world locally (the folder is usually called `world` unless you changed it) into your clients saves folder. You should be able to launch it and get into the world in order to remove the RS crafter or ET assembler. Once that is done close the save and then upload the save back to your server. It should work now, assuming you or someone else doesn't place the blocks next to each other again.

**Comment by Gh3ttoboy** [comment]
another thing i did to temporary fix this was just remove the 5 mods related to enviromental tech and just log in make sure nothing is connected to the block then shutting the server off and putting the mods back in

**Comment by BedrockLegends** [comment]
[crash-2020-11-29_19.20.09-client.txt](https://github.com/ValkyrieofNight/EnvironmentalTech/files/5613298/crash-2020-11-29_19.20.09-client.txt)

**Comment by BedrockLegends** [comment]
[crash-2020-11-29_19.22.13-server.txt](https://github.com/ValkyrieofNight/EnvironmentalTech/files/5613308/crash-2020-11-29_19.22.13-server.txt)

[debug.log](https://github.com/ValkyrieofNight/EnvironmentalTech/files/5613309/debug.log)

[latest.log](https://github.com/ValkyrieofNight/EnvironmentalTech/files/5613310/latest.log)

**Comment by ReillyBrogan** [comment]
@ValkyrieofNight I assume this has been fixed in 3.0.4.1? (there's no changelog on that jar)

**Comment by BedrockLegends** [comment]
yea @ReillyBrogan I noticed he does not provide a changelog, so some of us don't know what's been changed or not changed

**Comment by ValkyrieofNight** [comment]
Actually this was a bug in ValkyrieLib and it is in that changelog.
