### ISSUE TITLE
Tier 5 Void Miner won't construct

### ISSUE THREAD

**Issue by Shadowfire86** [ValkyrieofNight/EnvironmentalTech#250]
I'm playing on a Direwolf Server and I have verified multiple times that I have all the correct Blocks (Tier 5 controller, 6 laser cores, a Lens Holder, 70 Tier 5 Frames, 36 Structure Panels, 16 Null Modifiers, an Item Output and an FE Input, however I shift+right click, or right click on the controller nothing happens. No message, no building. (Direwolf Version 1.3.0 which contains Envirocore 3.0.6.0 and Envirotech 3.0.6.1) Edit: Managed to get it to construct. First problem was no information about the new Auto Utility Button. Second Problem was it apparently didn't like a lens holder or laser core as the first item in my inventory.

**Comment by PieterVenter7** [comment]
May I ask what auto utility button?

**Comment by ValkyrieofNight** [comment]
The shift right click functionality was replaced with a gui and this was mentioned in the changelog of valkyrielib. The auto constructor doesn't care what order you have the items in your inventory. The only thing that currently prevents the auto constructor from starting is if your player is not facing a valid direction for building the muktiblock. It relies on two directions currently in order to construct in the correct direction, the ccu direction and the players facing direction. 

Keep in mind this mod is in alpha and very work in progress. Many of the systems and features including the auto utility are not finished.
