### ISSUE TITLE
[1.16.4-3.0.6] Invalid construction direction

### ISSUE THREAD

**Issue by pnieuwkamp** [ValkyrieofNight/EnvironmentalTech#251]
Hi,

I'm playing the Direwolf20 1.6.4 1.3.1 pack (using MultiMC 5), and 90% of the time when I try to get the Litherite Void Miner CCU to build it's telling me "Invalid construction direction".

The white end of the miner is pointing down, there is nothing directly below it but ~60 'blocks' of air and then bedrock, and every now and then it does work? When it does build, it builds in the expected direction, down. I don't even have to close the window, just clicking again a few seconds after the error message goes away will eventually result in building the multiblock.

It doesn't matter if I have barely enough blocks, or stacks and stacks of them.

In order to make sure this isn't a mod conflict, I created a new 1.16.4 instance, with nothing more than:
- Minecraft 1.16.4
- Forge 35.1.36
- valkyrielib-1.16.4-3.0.6.1
- envirocore-1.16.4-3.0.6.0
- envirotech-1.16.4-3.0.6.1

and there I still get that error message. I get it less often, but I still get the error ~30% if the time. I tried pointing the miner in a different direction (watch?v=GB7CvGQ7I40 / "Introduction to Environmental Tech 3 1.16.4 - Void Miners" told me it no longer has to point down) but that has the same issue.

Also, for the auto-destruct to function I usually (but not always) have to break the first block myself? Is that worthy of its own issue or are the two related?

On a related note, the error message itself could use some work:
- it took me 15 minutes of trying before I even noticed there was an error message at all
- the error message is quite unreadable if the menu is still open (which it will be 99% of the time, as shift-right-clicking doesn't give an error at all; it just does nothing)
- it fades out quickly
- it is not in the chat-box for future reference

**Comment by ValkyrieofNight** [comment]
Invalid construction direction means your player is facing the wrong direction when trying to construct. The miner relies on the players facing direction to form the multiblocks in the correct orientation. 

The miner not destruction when the multiblock is formed is a known bug and is on my todo list to fix.

Keep in mind this mod is in alpha and very work in progress so expect things to change with updates. Nothing in the mod is considered final.

**Comment by pnieuwkamp** [comment]
I appreciate the effort that goes into it, and I understand that the mod is alpha :) 

I did some testing, it appears there is a 90 degree 'cone' around the miner in which the auto-build succeeds, and everywhere outside the cone building fails. I can think of a reason if the player is 'below' the miner; to prevent suffocation, but that isn't obvious from the message, and building also fails when the player is 'above' the miner.

![image](https://user-images.githubusercontent.com/13655588/104226463-22040780-5448-11eb-80a2-3a01d7d24f78.png)

Do you know why the miner relies on the direction the player is looking? It's not using it to determine which way to build (it's always building in the direction the miner is placed), so I'm curious why this happens.

**Comment by uecasm** [comment]
It does seem weird that it relies on the player's facing direction.  Since I want there to be enough space to place blocks below and surrounding it, that means I'm placing the void miner block itself in the middle of empty space, so the most logical place to be is when trying to build it is therefore standing on top of it looking down.  But this is apparently an "invalid direction".

**Comment by ValkyrieofNight** [comment]
As I said before it relies on two directions to form it in the right orientation due to the framework supporting asymmetrical multiblocks in any orientation. So the only two known directions to the controller are the players direction and the placement direction. The players direction must be perpendicular to the controllers placement direction for it to work. This system is temporary until I get the time to implement the system that I have planned that will replace the current single construction button.

**Comment by ValkyrieofNight** [comment]
As I said before it relies on two directions to form it in the right orientation due to the framework supporting asymmetrical multiblocks in any orientation. So the only two known directions to the controller are the players direction and the placement direction. The players direction must be perpendicular to the controllers placement direction for it to work. This system is temporary until I get the time to implement the system that I have planned that will replace the current single construction button.

**Comment by uecasm** [comment]
But why does it care about a perpendicular orientation at all?  The placement of the multiblock can be entirely defined by the placement of the controller block, since the structure is purely symmetric and can only be in one of the six placements specifically determined by that block alone.

The only asymmetric variation is where it places the I/O blocks, but it never places those correctly anyway (and quite frankly it would be better if it didn't even try to, I always have to move at least one of them).

**Comment by ValkyrieofNight** [comment]
You clearly didnt read what I said. As I said in my last post it currently requires both directions to form and this is entirely temporary because the final method of constructing the multiblocks is not complete. 

Also keep in mind this mod is FREE and is in alpha and I do not have infinite time to work on it. If you can't handle the quirks and work in progress systems of alpha mods I suggest not playing them.

**Comment by uecasm** [comment]
I did read what you said.  I also pointed out that what you said made absolutely no sense with the mod in its current form.  I even suggested two different better ways to do it (one of which even still uses the player facing direction, but in such a way that they're more likely to be facing correctly; if you did want to introduce asymmetric schematics in the future.  Though I don't see the point if it just complicates everything).

And I wasn't the one who added your mod to a modpack.  Clearly someone thinks it's ready to use.

**Comment by pnieuwkamp** [comment]
@ValkyrieofNight Why such hostile reactions?

I really don't mind quirks in works in progress, but I'm a programmer too (though I've never made a Minecraft mod) and I know showing a meaningful error message is often just as easy as showing one that isn't meaningful. You know why something happens (for instance, why the construction direction is invalid), we don't, and we rely on you to tell us.

I opened this issue because right now, it's totally unclear (until you start experimenting) what is happening. It's pretty common in Minecraft to use the direction a player is facing to determine which way to place a block, but in this case the block is already placed, and is already facing the right direction. This makes it hard for the player to figure out that it's not just the orientation of the controller, but also their own direction (especially because the miner only has one direction it can go relative to the controller). Which ties in to my previous paragraph; it would have been trivial to write 
`AddChatMessage "Invalid construction direction - try facing a different direction" -TextColor red`
instead of
`ShowError "Invalid construction direction" -time 500ms`

We 'need' (in quotes; you don't owe us anything) you to create this awesome mod, but most mod authors welcome feedback from the users of their mod. I'm providing feedback about what I think is unclear. Your explanation that is also uses the way the player is facing is immensely helpful in figuring out how to build the multiblock, because neither the video you made nor the error message tell us. And other people who run into this have to go to the Github issues page to find it.

The only reason we provide feedback is because we care enough about the mod to do so. I **like** Environmental Tech, so I want to help.

**Comment by MARTIKRISO** [comment]
He has explained how it works and why it works like that. As ValkyrieofNight has said multiple times, the mod is in alpha. Nothing is 100% permanent. A better message will probably be added, it's just not the highest priority. As this is not a bug, please refrain from writing in this issue. If you still need help, feel free to join the Discord server.

**Comment by MageWolf93** [comment]
with what ValkyrieofNight is saying it right there is not need to accuse him of being hostile when all he was saying is to try and help you, he has stated that the mod is in alpha state at the moment and i can confirm this due to there is a group of us testing the mod out making sure that its in a play able state for people to play you need to be patient with the features as there is a lot planed for it, a lot of us testers have had our fare share of issues that we all have come across and a lot of them are a lot worse than you can think of im not here to back anyone up im here to settle this dispute that is going on at this time

with placing it you need to make sure you have enough space in the area for it to build and i would recommend not standing in the area your going to be building it as it will sometimes not like it at its current state

when it says invalid construction detection or direction that's only a place holder at the moment

so once again please don't bring hate to what someone is doing for free out of there spare time as when people do that it will make developers just drop the mod completely and sometimes will never go back in to it again and just leave the project abandoned at its current state 

we understand that there is people that want to help but some people do need to understand the pressure of being a developer can have on people with keeping up expectations 

as martikiso said we do have a discord where can be the best place to help we all help each other with what ever this issue is

**Comment by pnieuwkamp** [comment]
"He has explained how it works and why it works like that."
Yes. And apparently people are not allowed to comment on that.

"As ValkyrieofNight has said multiple times, the mod is in alpha. Nothing is 100% permanent."
I don't know why people keep. bringing. that. up. when nobody is disputing that or even expecting everything to work. As you should be able to read I'm only trying to tell you that I ran into an issue. The issue / cause / fix / workaround / path forward has been explained to me. But, as I said, apparently people are not allowed to give feedback or ask clarification on that.

"with what ValkyrieofNight is saying it right there is not need to accuse him of being hostile when all he was saying is to try and help you"
It's the tone that makes the music. 

I like the mod, I appreciate the effort that goes into it, and I know it takes a lot of time, but don't accuse people of not being able to read when you don't understand that we read those comments with the knowledge of the mod WE have instead of the knowledge of the mod YOU have, or when you give us new information with the phrase "as I said before".

I'll leave it at that, as I don't want to add fuel to the fire. Rest assured, I won't be posting any more bug reports or issues that I may find.
