### ISSUE TITLE
Some console issues on startup

### ISSUE THREAD

**Issue by cauliflower69** [ValkyrieofNight/EnvironmentalTech#42]
https://pastebin.com/9nzTqq5G

Version: environmentaltech-1.11.2-0.11.0d

**Comment by dabigmoose** [comment]
Confirmed, I am having same issue.

**Comment by ValkyrieofNight** [comment]
Sorry 1.11.2 is no longer supported due to MC 1.12 and ET 2. ET 2 may be back-ported at some point however.

**Comment by danielm59** [comment]
This is causing me major issues trying to run a server as monitoring logs is impossible due to the spam from this error. I will not consider your mods in any of my future packs as you don't care about major bugs in one of the most active versions of MC.

**Comment by ValkyrieofNight** [comment]
Well its not that I don't care about 1.11.2 its that I do not have a lot of time. I don't have time to work on 3 versions of the mod at a time. 1.10.2 is the current most active version and 1.12 is being rapidly adopted due to being an easy port from 1.11.2. And if you read the comment I made it said that ET 2 might be back ported to 1.11.2 at some point. This all depends on how much people want it for that version. ET 1 is no longer supported in general due to ET 2 being the new ET.

**Comment by danielm59** [comment]
Well this is a major bug for server admins. I would remove it but have to many people using the mod.
 I would try and fix it myself if It was open source.
