### ISSUE TITLE
whats lonsdaleite

### ISSUE THREAD

**Issue by zipraGE** [ValkyrieofNight/EnvironmentalTech#96]
not sure what it is for does it have a uses yet cause it clogs up my system so just wondering  what it is used for or is it wip

**Comment by shortybsd** [comment]
Lonsdaleite is for Wither Proof blocks. If you have JEI type @environmentaltech at the bottom then hover your mouse over the said block. There is a nice tool tip explaining what it is for :). Looks like the recipe json isn't implemented in just yet. Try filling up a 3x3 crafting table with just that to see if it makes a block. If so you are golder for spawning in withers without having to worry of it getting loose or having to goto the nether roof (bedrock) to find the perfect spot to spawn it.

**Comment by Stray216** [comment]
@shortybsd Pladium, Ionite and Aethium all have the same "Wither Proof, Only players can break". It's not any different in that regard. But since it's named "crystal" and there are stairs, slabs and brick versions of it (like there are for the other 6 crystals) and since it's neatly ordered behind the other 6 crystals makes it seem like a 7th tier crystal. Just that it has the same color as Aethium is odd. JUST A GUESS.

**Comment by ValkyrieofNight** [comment]
It was an unused item but now it is required for modifiers. All the block varients of it are also wither proof
